/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cryptography_project;

/**
 *
 * @author joshuatupas
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        DomasProjectSectionBtn = new javax.swing.JButton();
        exitToLoginPageBtn = new javax.swing.JButton();
        joshProjectSectionBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DomasProjectSectionBtn.setText("Patients Records");
        DomasProjectSectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DomasProjectSectionBtnActionPerformed(evt);
            }
        });
        jPanel1.add(DomasProjectSectionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        exitToLoginPageBtn.setText("Exit to Login Page");
        exitToLoginPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitToLoginPageBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitToLoginPageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        joshProjectSectionBtn.setText("File Verification");
        joshProjectSectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joshProjectSectionBtnActionPerformed(evt);
            }
        });
        jPanel1.add(joshProjectSectionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jButton1.setText("Password Management");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jTabbedPane1.addTab("Dashboard", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DomasProjectSectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DomasProjectSectionBtnActionPerformed
        this.dispose();
        new records().setVisible(true);
        //hope this is fine dom -adam
    }//GEN-LAST:event_DomasProjectSectionBtnActionPerformed

    private void exitToLoginPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitToLoginPageBtnActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_exitToLoginPageBtnActionPerformed

    private void joshProjectSectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joshProjectSectionBtnActionPerformed
        this.dispose();
        new FileIntegrityJT().setVisible(true);
    }//GEN-LAST:event_joshProjectSectionBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DomasProjectSectionBtn;
    private javax.swing.JButton exitToLoginPageBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton joshProjectSectionBtn;
    // End of variables declaration//GEN-END:variables
}
